services:
  - type: web
    name: agriyield-plus
    env: python
    plan: free
    buildCommand: |
      pyenv install 3.10.13
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
